### ISSUE TITLE
Notifications - Should show date and time of the occurrence.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#184]
Now that all notifications are displayed for each mobile user, the date and time for each notification should also be shown in the notification page.

Also, it could be more helpful if the notifications could be filtered by date. Otherwise it just seems list of notifications, nothing more, as shown below.

![Screenshot_20190531-105855_Fieldsight](https://user-images.githubusercontent.com/20319653/58691992-5202b200-83ad-11e9-97fd-27afcca971c9.jpg)

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications - Should show date and time of the occurrence.](https://trello.com/c/behRARI6/631-notifications-should-show-date-and-time-of-the-occurrence)

**Comment by hereyubaraj** [comment]
@santoshkhatrii Closing this issues, we have a problem with a date because `date` field is not received in the firebase messaging and only received from api. Hence it only shows the date if the notification were pulled from server.

@awemulya We are not saving the fcm message when we received because opening on the notification we always call notification api.

![device-2019-05-31-154236](https://user-images.githubusercontent.com/47551530/58698352-cee85880-83ba-11e9-8b2e-4330e15e31fa.png)
