### ISSUE TITLE
Newly assigned Project Name (of sites assigned) not appearing in the project list even after restarting the app.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#205]
The lack of 'sync' button after the first sync makes the situation even worse.

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Newly assigned Project name (of sites assigned) not appearing in the project list even after restarting the app.](https://trello.com/c/fa3GX7eP/650-newly-assigned-project-name-of-sites-assigned-not-appearing-in-the-project-list-even-after-restarting-the-app)

**Comment by hereyubaraj** [comment]
@santoshkhatrii The app will always pull the projects when user opens the app and if the internet connectivity is available Otherwise project from local storage will appear.
Fixes are made in [fixes of this issue](https://github.com/fieldsight/fieldsight-mobile/pull/173/commits/135771562601988081c31a8d4695668b3abad2d8)
