### ISSUE TITLE
Error on map view. Mobile app.

### ISSUE THREAD

**Issue by marceloscarone** [fieldsight/fieldsight-mobile#476]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Map View
![Screenshot_20191109_150258_org bcss collect android](https://user-images.githubusercontent.com/50563569/68533217-40321d00-0304-11ea-8341-98c37c8f1e23.jpg)
![Screenshot_20191109_150321_org odk collect android](https://user-images.githubusercontent.com/50563569/68533218-40321d00-0304-11ea-8768-951c309abe5e.jpg)

Trying to do a geotrace in fieldsight, it is not possible to have the view of the map layer. But in odk collect, you can visualize the map.

**Comment by konishon** [comment]
Hi! @marceloscarone thanks for reaching out
Sadly, In our last merge with ODKCollect, the google maps token was not present. Hence, making the map not visible. 

This has been addressed on https://github.com/fieldsight/fieldsight-mobile/tree/468-apk-filename-dynamic and will be fixed in the next app update, which would be tomorrow

**Comment by marceloscarone** [comment]
Thanks!!

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by konishon** [comment]
This fix is being rolled out but in the time being you can either get the apk with this fix from [here](https://github.com/fieldsight/fieldsight-mobile/releases/tag/v3.2.12)

**Comment by marceloscarone** [comment]
Now works very fine. Thanks a lot!

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
